AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  HashKeyElementName:
    Type: String
    Default: InventoryId
    Description: Hash Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: Hash Key Type
Resources:
  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  Inventory:
    Description: Alfredo's Inventory Table
    Value: !Ref InventoryTable